[versions]
agp = "8.12.2"
kotlin = "2.0.21"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
googleServicesversion = "4.4.3"
firebaseAuthV = "24.0.1"
firebaseDatabaseV = "22.0.0"
loginGoogleV = "21.4.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebaseAuth = {group = "com.google.firebase", name= "firebase-auth", version.ref = "firebaseAuthV"}
firebaseDatabase = {group = "com.google.firebase", name= "firebase-database", version.ref = "firebaseDatabaseV"}
loginGoogle = {group = "com.google.android.gms", name= "play-services-auth", version.ref = "loginGoogleV"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleService = {id = "com.google.gms.google-services", version.ref = "googleServicesversion"}

